---
title: "Stock Market Timing Signals"
author: Marco Heimann
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About the system
The [Stock Market Timing (SMT)](https://www.getrevue.co/profile/investingnewsletter/members) system aims to time entries and exits in the SPY ETF adopting a medium to long term investment style. The criteria for investment are a mix of quantitative tests and discretionary decisions. Quantitative methods include backtesting of rule-based strategies and statistical analysis of historical price movements. Discretionary decisions gauge the quantitative elements in the light of macroeconomic cycles, political events and money management. Performance wise the goal is to beat the SP500 by 10% annually. If the drawdown exceeds 20% the service is shut down.

# Performance


# Procedures
Subscribers receive an email on weekends before the open of the US-markets (usually on Monday). Since trades might exceptionaly occur on a daily basis subscribers should be able to enter the orders received through email. On average [AIS](https://www.getrevue.co/profile/investingnewsletter/members) produces two entry signals a week and exits the same number of postitions. 

# Brokerage
The preferred broker is [IBKR](http://interactivebrokers.com). There is a steep learning curve for handling trades, but lower comissions are worth it. 